[project]
name = "finetuned-llm"
version = "0.1.0"
description = "finetuned model testing"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.116.1",
    "ollama>=0.5.1",
    "pydantic>=2.11.7",
    "requests>=2.32.4",
    "streamlit>=1.47.0",
    "uvicorn>=0.35.0",
]
